# Generated by Django 4.0.3 on 2022-05-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(blank=True, max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=12, unique=True, verbose_name='Cedula')),
                ('fecha_ingreso', models.DateField(null=True, verbose_name='Fecha de Ingreso')),
                ('edad', models.PositiveIntegerField(blank=True, verbose_name='Edad')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electronico')),
                ('telofono', models.CharField(blank=True, max_length=10, verbose_name='Telofono')),
                ('tipo_usuario', models.CharField(blank=True, choices=[('1', 'Veterinario'), ('2', 'Vendedor')], max_length=1, verbose_name='Tipo de Usuario')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
