# Generated by Django 4.0.3 on 2022-05-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellidos',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=20, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telofono',
            field=models.CharField(max_length=10, null=True, verbose_name='Telofono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'Veterinario'), ('2', 'Vendedor')], max_length=1, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
