# Generated by Django 4.0.3 on 2022-05-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_apellidos_alter_user_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'Veterinario'), ('2', 'Vendedor'), ('3', 'Administrador')], max_length=1, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
